version: '3.8'

services:
  db:
    env_file:
      - .env
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - websrv

  webapp:
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - websrv

networks:
  websrv:
