version: '3.3'

services:
  db:
    env_file:
      - .env
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --max_connections=1000
    restart: always
    ports:
      - "3306:3306"
    networks:
      - websrv

  webapp:
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - GUNICORN_WORKERS=150
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    restart: always
    depends_on:
      - db
    networks:
      - websrv

networks:
  websrv:

volumes:
  db_data:
