groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            roles: [ dialogs-api ]
            roles_cfg:
              dialogs-api:
                host: '0.0.0.0'
                port: 8080
